### PR TITLE
Update all helper scripts to new layout code

### PR DESCRIPTION
**Pull request by tskisner**
Fix names of detector properties and change plotting tools to work with both focalplane and xi/eta conventions.  Layout seems correct when used with the [corresponding toast branch](https://github.com/hpc4cmb/toast/pull/674), with the exception of the SAT LF and MLF pixel spacing.  Still working on that.

### CODE REVIEW

**Comment by tskisner** [comment]
This work now contains a manual merge of changes in the DC0 branch, and implements the intended focalplane layout found there.  Based on offline discussion, we plan to merge this PR into the branch in PR #28, and then merge that PR into master.  After verifying everything at that point, we can delete the DC0 branch and make a tag before re-running dc0.

Because the zoom-able PDF plots are large, you can [find them on dropbox here](https://www.dropbox.com/sh/2zl9y6o5dyjo29s/AAC5GtkT1mTbwM_bQv5gBIkOa?dl=0).  The `DC0_branch` folder has a script (`sim_test.sh`) used to generate those plots with the DC0 branch.  The `TK_branch` contains plots made with this PR and the `sim_test.sh` script in that directory.  All plots are in Xi / Eta sky projection coordinates with decreasing elevation in the downward direction.

# LAT

The main difference for these single-tube wafers is the overall rotation of the focalplane, and possibly a correction (flip) in the wafer layout.  There is still a question of whether the HF pin hole is oriented correctly.  That would be easy to change if the correct orientation is known.
chlat pdf
chlat_f030 pdf
chlat_f090 pdf
chlat_f220 pdf

# SAT

## 30GHz (rhombi-hex wafers)

Wafer spacing corresponds to 7.22 degrees, confirmed on plot by taking distance between corresponding pixels in two tubes.  Pixel spacing is 31.1mm = 1.84 degrees.  FWHM is 85.2 arcminutes = 1.42 degrees.  So the sizes on the plot make sense.
sat_f030 pdf
sat_f030_zoom

## 85GHz (rhombi-hex wafers)

Wafer spacing corresponds to 8.53 degree, again confirmed with differencing pixel coordinates on the plots.  Pin holes aligned to match the plots in the DC0 branch.
sat_f085 pdf
sat_f085_zoom

## 95GHz (hex wafers)

Wafer spacing is 8.52 degrees, confirmed on plot.  Wafers rotated so that pin holes align with DC0 branch.
sat_f095 pdf
sat_f095_zoom

## 220GHz (hex wafers)

Wafer spacing at 8.47 degrees, matching the plot.  Pin locations aligned with DC0 branch.
sat_f220 pdf
sat_f220_zoom

**Comment by smsimon** [comment]
And is there a Pole LAT to look at too?

**Comment by smsimon** [comment]
Are we sure the pixel spacings are right? 31.1*0.0700=2.177 deg

**Comment by tskisner** [comment]
Ah, I see now that for SAT_LF, the platescale was updated in your DC0 branch and I missed that when manually propagating the changes to this PR.  So it was still using the old value of 0.0592.  I'll fix that and make some plots of the SPLAT for comparison.

About the 90 degree LAT rotation- I thought that was one of the things that was wrong with the old code?  Should the LAT HF tube layout be "longer" in the azimuth or elevation directions?

**Comment by smsimon** [comment]
Verified that all other instrumental properties are correctly copied over, and that the pinhole clocking on SATs is correct. (There isn't currently a specified clocking for wafers in the the LAT tubes). Let me check more on the 90 degree layout thing for the LATs.

**Comment by tskisner** [comment]
I believe this is now implemented (LAT orientation on sky and SAT LF fixes).  Updated hardware files and plots are now in the [same drop box link](https://www.dropbox.com/sh/wk80oqfsx3clj1h/AAA9QjqSAdV53SOQ9HAC19dWa?dl=0).
chlat pdf
splat pdf

**Comment by smsimon** [comment]
The HF wafers in the LATs should have the same orientation as the rest of the wafers. I'd put them pin/slot pointing up to match the MF wafers

**Review by smsimon — APPROVED** [review]

**Pull request merged**
