### PR TITLE
Toast3 focalplane

### PR DESCRIPTION
**Pull request by keskitalo**
This PR is against #19 not against master.

### CODE REVIEW

**Comment by smsimon** [comment]
In a few places you have the band names. If those are supposed to correspond to the instrument model labels, then they'd need to be updated to match the new convention.
    "SPLAT_f020"
    "CHLAT_f030"
    "CHLAT_f040"
    "SPLAT_f030"
    "SPLAT_f040"
    "SAT_f030"
    "SAT_f040"
    "CHLAT_f090"
    "CHLAT_f150"
    "SPLAT_f090"
    "SPLAT_f150"
    "SAT_f085"
    "SAT_f145"
    "SAT_f095"
    "SAT_f155"
    "CHLAT_f220"
    "CHLAT_f280"
    "SPLAT_f220"
    "SPLAT_f280"
    "SAT_f220"
    "SAT_f280"

**Comment by keskitalo** [comment]
Thanks. Those band labels are in design tool simulation files that have evolved since you branched DC1. They should not matter for this work.

**Comment by keskitalo** [comment]
Merging this uncontroversial script.

**Comment by smsimon** [comment]
Great!

**Pull request merged**
