### PR TITLE
Draft pre-baseline design (85-tube LATs, SAT tube config)

### PR DESCRIPTION
**Pull request by smsimon**
Rough draft of the 85 tube LAT design
Tube spacings/scalings provided by Brad Benson from the LAT group
Tube placement has not been decided yet, so this is using a place holder with highest frequencies in the center
Tubes documentation in s4sim/s4sim/hardware.py has not yet been updated since the tube mapping is in flux
Should modify this as more information on the instrument side becomes available prior to merging

### CODE REVIEW

**Comment by smsimon** [comment]
Note: Still need to disable elevation noise scaling for Chile LAT

**Comment by smsimon** [comment]
Remaining inputs: SPSAT and SPLAT elevation scalings

**Comment by zonca** [comment]
bandpasses, beams and tube labels are stable now, so I am going to start running the foreground/CMB simulations for the next round of Design Tool simulations.
I am going to export the instrument model using commit ca07638, please do not rebase/squash, so that that this commit hash is preserved.

**Comment by zonca** [comment]
@keskitalo @smsimon I cannot find an explanation for the meaning of the new labels, the ones with `P`:

```
odict_keys(['ULFPL1', 'LFL1', 'LFL2', 'LFPL1', 'LFPL2', 'LFS1', 'LFS2', 'MFL1', 'MFL2', 'MFPL1', 'MFPL2', 'MFLS1', 'MFLS2', 'MFHS1', 'MFHS2', 'HFL1', 'HFL2', 'HFPL1', 'HFPL2', 'HFS1', 'HFS2'])
```

is that for Pole?
do I need to simulate only the ones with P at Pole and only the others in Chile?

**Comment by jdborrill** [comment]
I presume this is marking the distinction between the Pole LAT (now
baseined as the TMA) and the Chile LATs (still CCAT/SO-design). For
consistency I'd suggest adding a "C" to the Chile LATs.

Julian

**Comment by keskitalo** [comment]
Yes the bands with "P" are for Pole LAT. Same names without "P" are for the Chile LATs. The rest are Pole SAT bands. There will not be dedicated numbers for the redeployed SATs in Chile so you can reuse them.

**Comment by jdborrill** [comment]
Can we add "C" to the Chile LATs or does that break something?

J

**Comment by keskitalo** [comment]
I would be a good idea, since the NET calculations are site-specific. However, I would prefer not confusing things now that the design tool sims that use the band names are already underway.

**Comment by jdborrill** [comment]
OK - can we flag it for DC1?

Julian

**Comment by smsimon** [comment]
Yes, we flag that. For completeness:
"ULFPL1"-Ultra low frequency Pole LAT, band 1 (20 GHz)
"LFL1"- Low frequency Chile LAT, band 1 (30 GHz)
"LFL2"- Low frequency Chile LAT, band 2 (40 GHz)
"LFPL1"- Low frequency Pole LAT, band 1 (30 GHz)
"LFPL2"- Low frequency Pole LAT, band 2 (40 GHz)
"LFS1"- Low frequency Pole SAT, band 1 (30 GHz)
"LFS2"- Low frequency Pole SAT, band 2 (40 GHz)
"MFL1"- Mid frequency Chile LAT, band 1 (90 GHz)
"MFL2"- Mid frequency Chile LAT, band 2 (150 GHz)
"MFPL1"- Mid frequency Pole LAT, band 1 (90 GHz)
"MFPL2"- Mid frequency Pole LAT, band 2 (150 GHz)
"MFLS1"- Mid frequency Lower Pole SAT, band 1 (85 GHz)
"MFLS2"- Mid frequency Lower Pole SAT, band 2 (145 GHz)
"MFHS1"- Mid frequency Lower Pole SAT, band 1 (85 GHz)
"MFHS2"- Mid frequency Lower Pole SAT, band 2 (145 GHz)
"HFL1"- High frequency Chile LAT, band 1 (220 GHz)
"HFL2"- High frequency Chile LAT, band 2 (270 GHz)
"HFPL1"- High frequency Pole LAT, band 1 (220 GHz)
"HFPL2"- High frequency Pole LAT, band 2 (270 GHz)
"HFS1"- High frequency Pole SAT, band 1 (220 GHz)
"HFS2"- High frequency Pole SAT, band 2 (270 GHz)

**Comment by zonca** [comment]
I see that there are 3 LAT telescopes, `LAT0`, `LAT1`, `LAT2`,
but each of them seems to have both Pole and Chile tubes:

```
c.data["telescopes"]["LAT0"]["fwhm"]
OrderedDict([('ULFPL1', 10.0),
             ('LFL1', 7.4),
             ('LFPL1', 7.4),
             ('LFL2', 5.1),
             ('LFPL2', 5.1),
             ('MFL1', 2.2),
             ('MFPL1', 2.2),
             ('MFL2', 1.4),
             ('MFPL2', 1.4),
             ('HFL1', 1.0),
             ('HFPL1', 1.0),
             ('HFL2', 0.9),
             ('HFPL2', 0.9)])
```

**Comment by smsimon** [comment]
That is just the standard fwhm dictionary for all of them. The telescopes themselves only have one type of Chile/Pole tube

**Comment by keskitalo** [comment]
I made an issue: https://github.com/CMB-S4/s4sim/issues/18

**Comment by zonca** [comment]
I am exporting again using `8cdd47c`, @keskitalo please make sure that changes in Pole LAT fwhm do not impact the sims you are already running.

The exported version of the instrument model is at https://github.com/CMB-S4/s4mapbasedsims/blob/202102_design_tool_run/202102_design_tool_run/instrument_model/cmbs4_instrument_model.tbl

**Comment by smsimon** [comment]
That all looks correct

**Comment by zonca** [comment]
I am preparing another run, I am exporting 9a643f5e86d322487a671d98d67f6716814cee80

**Pull request merged**
